package np_cpu

import chisel3.iotesters._

class topTests (top : top) extends PeekPokeTester(top) {
  println("$s2 = 42 , $s3 = 33")
  println("ADD $s1 $s2 $s3")
  // println("opcode = " + peek(top.io.opcode).toString)
  // println("rs_addr = " + peek(top.io.rs).toString)
  // println("rt_addr = " + peek(top.io.rt).toString)
  // println("rd_addr = " + peek(top.io.rd).toString)
  // println("shamt = " + peek(top.io.shamt).toString)
  // println("func = " + peek(top.io.func).toString)
  // println("imm_16 = " + peek(top.io.imm_16).toString)
  // println("imm_26 = " + peek(top.io.imm_26).toString)
  // println("rdata1 = " + peek(top.io.rdata1).toString)
  // println("rdata2 = " + peek(top.io.rdata2).toString)
  // println("alu_src2 = " + peek(top.io.alu_src2).toString)
  // println("reg_dst = " + peek(top.io.reg_dst).toString)
  // println("ALUCtrl = " + peek(top.io.ALUCtrl).toString)
  println("ALUout = " + peek(top.io.ALUout).toString)
  println("===========================")
  step(1)
  println("ORI $s1 $s2  56")
  // println("opcode = " + peek(top.io.opcode).toString)
  // println("rs_addr = " + peek(top.io.rs).toString)
  // println("rt_addr = " + peek(top.io.rt).toString)
  // println("rd_addr = " + peek(top.io.rd).toString)
  // println("shamt = " + peek(top.io.shamt).toString)
  // println("func = " + peek(top.io.func).toString)
  // println("imm_16 = " + peek(top.io.imm_16).toString)
  // println("imm_26 = " + peek(top.io.imm_26).toString)
  // println("rdata1 = " + peek(top.io.rdata1).toString)
  // println("rdata2 = " + peek(top.io.rdata2).toString)
  // println("alu_src2 = " + peek(top.io.alu_src2).toString)
  // println("reg_dst = " + peek(top.io.reg_dst).toString)
  // println("ALUCtrl = " + peek(top.io.ALUCtrl).toString)
  println("ALUout = " + peek(top.io.ALUout).toString)
  println("===========================")
  step(1)
  println("LW $s1 4(%s4)")
  // println("opcode = " + peek(top.io.opcode).toString)
  // println("rs_addr = " + peek(top.io.rs).toString)
  // println("rt_addr = " + peek(top.io.rt).toString)
  // println("rd_addr = " + peek(top.io.rd).toString)
  // println("shamt = " + peek(top.io.shamt).toString)
  // println("func = " + peek(top.io.func).toString)
  // println("imm_16 = " + peek(top.io.imm_16).toString)
  // println("imm_26 = " + peek(top.io.imm_26).toString)
  // println("rdata1 = " + peek(top.io.rdata1).toString)
  // println("rdata2 = " + peek(top.io.rdata2).toString)
  // println("alu_src2 = " + peek(top.io.alu_src2).toString)
  // println("reg_dst = " + peek(top.io.reg_dst).toString)
  // println("ALUCtrl = " + peek(top.io.ALUCtrl).toString)
  println("ALUout = " + peek(top.io.ALUout).toString)
  println("===========================")
  step(1)
  println("SW $s3  24(%s4)")
  // println("opcode = " + peek(top.io.opcode).toString)
  // println("rs_addr = " + peek(top.io.rs).toString)
  // println("rt_addr = " + peek(top.io.rt).toString)
  // println("rd_addr = " + peek(top.io.rd).toString)
  // println("shamt = " + peek(top.io.shamt).toString)
  // println("func = " + peek(top.io.func).toString)
  // println("imm_16 = " + peek(top.io.imm_16).toString)
  // println("imm_26 = " + peek(top.io.imm_26).toString)
  // println("rdata1 = " + peek(top.io.rdata1).toString)
  // println("rdata2 = " + peek(top.io.rdata2).toString)
  // println("alu_src2 = " + peek(top.io.alu_src2).toString)
  // println("reg_dst = " + peek(top.io.reg_dst).toString)
  // println("ALUCtrl = " + peek(top.io.ALUCtrl).toString)
  println("ALUout = " + peek(top.io.ALUout).toString)
  println("===========================")
  step(1)
}

object topTests extends App {
  Driver(() => new top()) {top =>
    new topTests(top)
  }
}